-- MySQL Script generated by MySQL Workbench
-- Tue Apr 19 14:51:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `Id_Departamento` INT NOT NULL AUTO_INCREMENT,
  `Nom_Departamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `Id_Ciudad` INT NOT NULL AUTO_INCREMENT,
  `Nom_Ciudad` VARCHAR(100) NOT NULL,
  `Id_Departamento` INT NOT NULL,
  PRIMARY KEY (`Id_Ciudad`),
  CONSTRAINT `fk_Ciudad_Departamento`
    FOREIGN KEY (`Id_Departamento`)
    REFERENCES `mydb`.`Departamento` (`Id_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Departamento_idx` ON `mydb`.`Ciudad` (`Id_Departamento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  `Direccion` VARCHAR(150) NOT NULL,
  `Id_Ciudad` INT NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  CONSTRAINT `fk_Usuario_Ciudad`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `mydb`.`Ciudad` (`Id_Ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Ciudad_idx` ON `mydb`.`Usuario` (`Id_Ciudad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `Id_Cuenta` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(255) NOT NULL,
  `Fecha_Registro` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Cuenta`),
  CONSTRAINT `fk_Cuenta_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Usuario_idx` ON `mydb`.`Cuenta` (`Id_Usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `Id_Carrito` INT NOT NULL AUTO_INCREMENT,
  `Id_Usuario` INT NOT NULL,
  `Tiempo_Creacion` DATETIME NOT NULL,
  PRIMARY KEY (`Id_Carrito`),
  CONSTRAINT `fk_Carrito_Usuario`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `mydb`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Usuarios_idx` ON `mydb`.`Carrito` (`Id_Usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `Id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Cat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tallas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tallas` (
  `Id_Tallas` INT NOT NULL AUTO_INCREMENT,
  `Nombres_Talla` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Tallas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `Id_Producto` INT NOT NULL AUTO_INCREMENT,
  `Id_Categoria` INT NOT NULL,
  `Nombre_Producto` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Id_Tallas` INT NOT NULL,
  `Precio_Unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`Id_Producto`),
  CONSTRAINT `fk_Producto_Categoria`
    FOREIGN KEY (`Id_Categoria`)
    REFERENCES `mydb`.`Categoria` (`Id_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Tallas`
    FOREIGN KEY (`Id_Tallas`)
    REFERENCES `mydb`.`Tallas` (`Id_Tallas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Categoria_idx` ON `mydb`.`Producto` (`Id_Categoria` ASC) VISIBLE;

CREATE INDEX `Id_Tallas_idx` ON `mydb`.`Producto` (`Id_Tallas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Detalles_Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalles_Carrito` (
  `Id_Carrito` INT NOT NULL,
  `Id_Producto` INT NOT NULL,
  `Cantidad` TINYINT NOT NULL,
  PRIMARY KEY (`Id_Carrito`, `Id_Producto`),
  CONSTRAINT `fk_DetallesCarrito_Carrito`
    FOREIGN KEY (`Id_Carrito`)
    REFERENCES `mydb`.`Carrito` (`Id_Carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetallesCarrito_Producto`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `mydb`.`Producto` (`Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Producto_idx` ON `mydb`.`Detalles_Carrito` (`Id_Producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilidad` (
  `Id_Stock` INT NOT NULL AUTO_INCREMENT,
  `Id_Producto` INT NOT NULL,
  `Cantidad_Disponible` INT NOT NULL,
  `Cantidad_Reservada` INT NOT NULL,
  `Cantidad_Vendida` INT NOT NULL,
  PRIMARY KEY (`Id_Stock`),
  CONSTRAINT `fk_Disponibilidad_Producto`
    FOREIGN KEY (`Id_Producto`)
    REFERENCES `mydb`.`Producto` (`Id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Producto_idx` ON `mydb`.`Disponibilidad` (`Id_Producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Pedido` (
  `Id_Estado_Pedido` TINYINT NOT NULL AUTO_INCREMENT,
  `Nombre_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Estado_Pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `Id_Pedido` INT NOT NULL AUTO_INCREMENT,
  `Id_Carrito` INT NOT NULL,
  `Tiempo_Pedido` DATETIME NOT NULL,
  `Id_Estado_Pedido` TINYINT NOT NULL,
  PRIMARY KEY (`Id_Pedido`),
  CONSTRAINT `fk_Pedido_Carrito`
    FOREIGN KEY (`Id_Carrito`)
    REFERENCES `mydb`.`Carrito` (`Id_Carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_EstadoPedido`
    FOREIGN KEY (`Id_Estado_Pedido`)
    REFERENCES `mydb`.`Estado_Pedido` (`Id_Estado_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Carrito_idx` ON `mydb`.`Pedido` (`Id_Carrito` ASC) VISIBLE;

CREATE INDEX `Id_Estado_Pedido_idx` ON `mydb`.`Pedido` (`Id_Estado_Pedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Metodo_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Metodo_Pago` (
  `Id_Met_Pago` TINYINT NOT NULL AUTO_INCREMENT,
  `Metodo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Met_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Pago` (
  `Id_Estado_Pago` TINYINT NOT NULL AUTO_INCREMENT,
  `Estado_Pago` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Estado_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `Id_Pago` INT NOT NULL AUTO_INCREMENT,
  `Id_Pedido` INT NOT NULL,
  `Id_Met_Pago` TINYINT NOT NULL,
  `Limite_Tiempo_Pago` DATETIME NOT NULL,
  `Tiempo_Pago` DATETIME NOT NULL,
  `Id_Estado_Pago` TINYINT NOT NULL,
  PRIMARY KEY (`Id_Pago`),
  CONSTRAINT `fk_Pago_Pedido`
    FOREIGN KEY (`Id_Pedido`)
    REFERENCES `mydb`.`Pedido` (`Id_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_MetodoPago`
    FOREIGN KEY (`Id_Met_Pago`)
    REFERENCES `mydb`.`Metodo_Pago` (`Id_Met_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_EstadoPago`
    FOREIGN KEY (`Id_Estado_Pago`)
    REFERENCES `mydb`.`Estado_Pago` (`Id_Estado_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Pedidos_idx` ON `mydb`.`Pago` (`Id_Pedido` ASC) VISIBLE;

CREATE INDEX `Id_Met_Pago_idx` ON `mydb`.`Pago` (`Id_Met_Pago` ASC) VISIBLE;

CREATE INDEX `Id_Estado_Pago_idx` ON `mydb`.`Pago` (`Id_Estado_Pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Envio` (
  `Id_Estado_Envio` TINYINT NOT NULL AUTO_INCREMENT,
  `Estado_Envio` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Estado_Envio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cambio_Direccion_Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cambio_Direccion_Entrega` (
  `Id_Direccion` INT NOT NULL AUTO_INCREMENT,
  `Direccion_Envio` VARCHAR(150) NOT NULL,
  `Id_Ciudad` INT NOT NULL,
  PRIMARY KEY (`Id_Direccion`),
  CONSTRAINT `fk_CambioDireccion_Ciudad`
    FOREIGN KEY (`Id_Ciudad`)
    REFERENCES `mydb`.`Ciudad` (`Id_Ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_ciudad_idx` ON `mydb`.`Cambio_Direccion_Entrega` (`Id_Ciudad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Envio` (
  `Id_Envio` INT NOT NULL AUTO_INCREMENT,
  `Id_Pedido` INT NOT NULL,
  `Id_Direccion` INT NOT NULL,
  `Fecha_Envio` DATE NOT NULL,
  `Fecha_Entrega` DATE NOT NULL,
  `Id_Estado_Envio` TINYINT NOT NULL,
  PRIMARY KEY (`Id_Envio`),
  CONSTRAINT `fk_Envio_Pedido`
    FOREIGN KEY (`Id_Pedido`)
    REFERENCES `mydb`.`Pedido` (`Id_Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envio_EstadoEnvio`
    FOREIGN KEY (`Id_Estado_Envio`)
    REFERENCES `mydb`.`Estado_Envio` (`Id_Estado_Envio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Envio_Direccion`
    FOREIGN KEY (`Id_Direccion`)
    REFERENCES `mydb`.`Cambio_Direccion_Entrega` (`Id_Direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Id_Pedido_idx` ON `mydb`.`Envio` (`Id_Pedido` ASC) VISIBLE;

CREATE INDEX `Id_Estado_Envio_idx` ON `mydb`.`Envio` (`Id_Estado_Envio` ASC) VISIBLE;

CREATE INDEX `Id_Direccion_idx` ON `mydb`.`Envio` (`Id_Direccion` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
